---
kind: pipeline
type: docker
name: default

steps:

- name: test
  image: alpine
  commands:
  - echo hello
  - echo world

- name: slack
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack-webhook
    channel: ecointet-channel
    icon_url: https://unsplash.it/256/256/?random