---
kind: pipeline
type: docker
name: default

steps:

- name: EasyBuild
  image: alpine
  commands:
  - echo hello
  - echo world

- name: build
  image: node:14-alpine
  commands:
    - apk add --no-cache git
    - npm i -g @nestjs/cli
    - npm ci
    - npm run build

- name: SlackNotification
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack-webhook
    channel: ecointet-channel
    icon_url: https://unsplash.it/256/256/?random